[package]
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "22.0.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
bytemuck = "1.16.1"
flume = "0.11.0"
log = "0.4.22"